services:
  - type: web
    name: recipes-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipes_db_nzs9
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PROD_PORT
        value: 10000