services:
  - type: web
    name: recipes-backend
    runtime: node
    buildCommand: cd server && npm install && npm run build
    startCommand: node dist/server.js  # Запускаем собранный файл из dist
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipes_db_nzs9
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000